appShortcuts:
- bundleIdentifier: company.thebrowser.Browser
  shortcut:
    key: a
    modifiers:
    - option
- bundleIdentifier: com.googlecode.iterm2
  shortcut:
    key: i
    modifiers:
    - option
- bundleIdentifier: notion.id
  shortcut:
    key: n
    modifiers:
    - option
- bundleIdentifier: com.apple.dt.Xcode
  shortcut:
    key: x
    modifiers:
    - option
- bundleIdentifier: com.spotify.client
  shortcut:
    key: s
    modifiers:
    - option
- bundleIdentifier: com.xlnaudio.addictivedrums2
  shortcut:
    key: m
    modifiers:
    - option
- bundleIdentifier: com.bitwarden.desktop
  shortcut:
    key: b
    modifiers:
    - option
- bundleIdentifier: org.alacritty
  shortcut:
    key: k
    modifiers:
    - option
- bundleIdentifier: com.microsoft.teams2
  shortcut:
    key: t
    modifiers:
    - option
- bundleIdentifier: com.apple.Safari
  shortcut:
    key: d
    modifiers:
    - option
- bundleIdentifier: com.microsoft.Outlook
  shortcut:
    key: o
    modifiers:
    - option
- bundleIdentifier: net.whatsapp.WhatsApp
  shortcut:
    key: w
    modifiers:
    - option
- bundleIdentifier: com.microsoft.VSCode
  shortcut:
    key: v
    modifiers:
    - option
- bundleIdentifier: com.tinyspeck.slackmacgap
  shortcut:
    key: l
    modifiers:
    - option
generalShortcuts:
- name: Remove current window from layout
  shortcut:
    key: p
    modifiers:
    - option
- name: Focus Screen 1
  shortcut:
    key: '1'
    modifiers:
    - command
    - control
- name: Focus Screen 2
  shortcut:
    key: '2'
    modifiers:
    - command
    - control
- name: Focus Screen 3
  shortcut:
    key: '3'
    modifiers:
    - command
    - control
- name: Focus Screen 4
  shortcut:
    key: '4'
    modifiers:
    - command
    - control
- name: Focus Screen 5
  shortcut:
    key: '5'
    modifiers:
    - command
    - control
- name: Focus Screen 6
  shortcut:
    key: '6'
    modifiers:
    - command
    - option
- name: Throw to Screen 1
  shortcut:
    key: '1'
    modifiers:
    - command
    - shift
- name: Throw to Screen 2
  shortcut:
    key: '2'
    modifiers:
    - command
    - shift
- name: Throw to Screen 3
  shortcut:
    key: '3'
    modifiers:
    - command
    - shift
- name: Throw to Screen 4
  shortcut:
    key: '4'
    modifiers:
    - command
    - shift
- name: Throw to Screen 5
  shortcut:
    key: '5'
    modifiers:
    - command
    - shift
- name: Throw to Screen 6
  shortcut:
    key: g
    modifiers:
    - command
    - shift
- name: Throw app to current layout modifier
  shortcut:
    key: ''
    modifiers: []
- name: Increase main panel count
  shortcut:
    key: ''
    modifiers: []
- name: Decrease main panel count
  shortcut:
    key: ''
    modifiers: []
- name: Cycle current layout windows clockwise
  shortcut:
    key: ''
    modifiers: []
- name: Cycle current layout windows counterclockwise
  shortcut:
    key: ''
    modifiers: []
- name: Toggle Full Screen layout for the current screen
- name: Toggle layout for current WindowSet
  shortcut:
    key: z
    modifiers:
    - option
settings:
  showLayoutIndicator: true
  showThrowNotifications: true
  notificationDuration: 1.5e+0
  notificationPosition: center
  launchAtLogin: false
  hideMenuBarIcon: false
  enableAccessibilityOnStart: true
  windowGap: 4e+0
  windowMargin: 0e+0
  defaultLayoutMode: wide
  animateWindowTransitions: true
  respectWindowMinimumSize: true
  autoExpandNewWindows: true
  enableDebugLogging: false
  showLogsView: false
  windowDetectionInterval: 5e-1
  focusFollowsMouse: false
