appShortcuts:
- bundleIdentifier: com.apple.iCal
  shortcut:
    key: f
    modifiers:
    - option
- bundleIdentifier: company.thebrowser.Browser
  shortcut:
    key: a
    modifiers:
    - option
- bundleIdentifier: com.googlecode.iterm2
  shortcut:
    key: i
    modifiers:
    - option
- bundleIdentifier: notion.id
  shortcut:
    key: n
    modifiers:
    - option
- bundleIdentifier: com.apple.dt.Xcode
  shortcut:
    key: x
    modifiers:
    - option
- bundleIdentifier: com.spotify.client
  shortcut:
    key: s
    modifiers:
    - option
- bundleIdentifier: org.alacritty
  shortcut:
    key: k
    modifiers:
    - option
- bundleIdentifier: com.runningwithcrayons.Alfred
  shortcut:
    key: ''
    modifiers: []
- bundleIdentifier: com.bitwarden.desktop
  shortcut:
    key: b
    modifiers:
    - option
- bundleIdentifier: com.apple.Safari
  shortcut:
    key: d
    modifiers:
    - option
- bundleIdentifier: com.tinyspeck.slackmacgap
  shortcut:
    key: l
    modifiers:
    - option
- bundleIdentifier: net.whatsapp.WhatsApp
  shortcut:
    key: w
    modifiers:
    - option
- bundleIdentifier: com.microsoft.VSCode
  shortcut:
    key: v
    modifiers:
    - option
- bundleIdentifier: com.openai.chat
  shortcut:
    key: o
    modifiers:
    - option
generalShortcuts:
- name: Remove current window from layout
  shortcut:
    key: ','
    modifiers:
    - option
- name: Toggle layout for current WindowSet
  shortcut:
    key: z
    modifiers:
    - option
- name: Focus Screen 1
  shortcut:
    key: ''
    modifiers: []
- name: Focus Screen 2
  shortcut:
    key: ''
    modifiers: []
- name: Focus Screen 3
  shortcut:
    key: ''
    modifiers: []
- name: Focus Screen 4
  shortcut:
    key: ''
    modifiers: []
- name: Focus Screen 5
  shortcut:
    key: ''
    modifiers: []
- name: Focus Screen 6
  shortcut:
    key: ''
    modifiers: []
- name: Throw to Screen 1
  shortcut:
    key: '1'
    modifiers:
    - command
    - shift
- name: Throw to Screen 2
  shortcut:
    key: '2'
    modifiers:
    - command
    - shift
- name: Throw to Screen 3
  shortcut:
    key: '3'
    modifiers:
    - command
    - shift
- name: Throw to Screen 4
  shortcut:
    key: ''
    modifiers: []
- name: Throw to Screen 5
  shortcut:
    key: ''
    modifiers: []
- name: Throw to Screen 6
  shortcut:
    key: ''
    modifiers: []
- name: Throw app to current layout modifier
  shortcut:
    key: t
    modifiers:
    - command
    - option
- name: Increase main panel size
  shortcut:
    key: y
    modifiers:
    - option
- name: Decrease main panel size
  shortcut:
    key: t
    modifiers:
    - option
- name: Expand Windows
  shortcut:
    key: .
    modifiers:
    - option
- name: Move Window Up in Layout
  shortcut:
    key: h
    modifiers:
    - option
- name: Move Window Down in Layout
  shortcut:
    key: g
    modifiers:
    - option
- name: Show layout visualization
  shortcut:
    key: r
    modifiers:
    - option
- name: Position Window Left
- name: Position Window Right
- name: Position Window Top
- name: Position Window Bottom
- name: Position Window Top Left
- name: Position Window Top Right
- name: Position Window Bottom Left
- name: Position Window Bottom Right
- name: Position Window Center
windowPreview:
  enabled: true
  maxWidth: 2e+2
  maxHeight: 1.5e+2
  cacheTimeoutSeconds: 5e+0
theme:
  accentColorRed: 0e+0
  accentColorGreen: 5e-1
  accentColorBlue: 1e+0
  accentColorAlpha: 1e+0
  activeWindowBorderWidth: 3e+0
  inactiveWindowOpacity: 7e-1
